'use strict';

// ── Site-wide constants ───────────────────────────────────────────────────────
const site = {
  name:      'Poki2',
  domain:    'https://poki2.online',
  tagline:   'The Ultimate Free Browser Games Network',
  faviconUrl:'https://poki2.online/favicon.svg',
};

// ── Subdomain network ─────────────────────────────────────────────────────────
const network = [
  {
    slug:        'play',
    name:        'Poki2 Play',
    url:         'https://play.poki2.online/',
    color:       '#22d3ee',
    emoji:       '🎮',
    status:      'live',
    gameCount:   '200+',
    categories:  'Action, Puzzle, Racing, Sports, Adventure',
    description: 'The original Poki2 game collection — over 200 hand-picked HTML5 games across every genre. Fast loading, no ads during gameplay, and works on any device.',
  },
  {
    slug:        'azgames',
    name:        'AZ Games',
    url:         'https://azgames.poki2.online/',
    color:       '#f97316',
    emoji:       '🕹️',
    status:      'live',
    gameCount:   '300+',
    categories:  'IO, Clicker, Adventure, 2-Player, Sports, Puzzle',
    description: 'A massive 300-game collection sorted A to Z, powered by the azgames.io catalog. Every genre is covered with fresh titles added regularly.',
  },
  {
    slug:        'gplus',
    name:        'Unblocked G+',
    url:         'https://unblocked-games-g-plus.poki2.online/',
    color:       '#a855f7',
    emoji:       '🔓',
    status:      'live',
    gameCount:   '474+',
    categories:  'Unblocked, School-Safe, Parkour, IO',
    description: "School-safe unblocked games in the G+ tradition. Works on Chromebook, survives most school firewalls, and includes the classics teachers haven't blocked yet.",
  },
  {
    slug:        'kids',
    name:        'Kids Games',
    color:       '#4ade80',
    emoji:       '🧒',
    status:      'soon',
    gameCount:   '100+',
    categories:  'Coloring, Matching, Friendly Platformers',
    description: 'Coming soon — a curated library of age-appropriate browser games for children aged 4–12. Safe for school, no ads, no in-app purchases.',
  },
  {
    slug:        'racing',
    name:        'Racing Hub',
    color:       '#f59e0b',
    emoji:       '🏎️',
    status:      'soon',
    gameCount:   '80+',
    categories:  'Drift, Formula, Off-Road, Stunt',
    description: 'Coming soon — the dedicated racing portal. Drift Hunters, Moto X3M, and dozens more racing games with instant browser play.',
  },
  {
    slug:        'puzzle',
    name:        'Puzzle World',
    color:       '#ec4899',
    emoji:       '🧩',
    status:      'soon',
    gameCount:   '120+',
    categories:  'Sudoku, Match-3, Logic, Word',
    description: 'Coming soon — dedicated to brain teasers and puzzle games. 2048, Cut the Rope, Mahjong, and hundreds of logic challenges.',
  },
  {
    slug:        'io',
    name:        'IO Arena',
    color:       '#6366f1',
    emoji:       '🌐',
    status:      'soon',
    gameCount:   '60+',
    categories:  'Multiplayer IO, Battle Royale, Survival',
    description: 'Coming soon — every major .io game in one place. Agar.io, Slither.io, Krunker, Shell Shockers and more with zero login required.',
  },
  {
    slug:        'stickman',
    name:        'Stickman Zone',
    color:       '#64748b',
    emoji:       '🥷',
    status:      'soon',
    gameCount:   '50+',
    categories:  'Action, Fighting, Parkour, Strategy',
    description: 'Coming soon — all things stickman. Hook, Archer, Sniper, and dozens of stickman action games in a single fast-loading portal.',
  },
];

// ── Static pages metadata ──────────────────────────────────────────────────────
const pages = [
  {
    slug:       'index',
    outputFile: 'index.html',
    bodyClass:  'home-page',
    title:      'Poki2 — Free Browser Games Network: 1000+ Games, No Download',
    description:'Poki2 is a free browser games network. Explore 1000+ games across 8 specialized sites — IO, action, puzzle, racing, and more. No downloads, instant play.',
    keywords:   'free browser games, online games no download, poki2, free online games, browser games network',
    canonical:  'https://poki2.online/',
    schema: [
      {
        '@context': 'https://schema.org',
        '@type': 'Organization',
        name: 'Poki2',
        url:  'https://poki2.online/',
        logo: 'https://poki2.online/favicon.svg',
        contactPoint: [{ '@type': 'ContactPoint', contactType: 'customer support', email: 'contact@poki2.online' }],
        sameAs: ['https://azgames.poki2.online', 'https://unblocked-games-g-plus.poki2.online'],
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebSite',
        url:  'https://poki2.online',
        name: 'Poki2',
        publisher: { '@type': 'Organization', name: 'Poki2', url: 'https://poki2.online/' },
        potentialAction: {
          '@type': 'SearchAction',
          target: { '@type': 'EntryPoint', urlTemplate: 'https://azgames.poki2.online/?q={search_term_string}' },
          'query-input': 'required name=search_term_string'
        }
      },
    ],
  },
  {
    slug:       'about',
    outputFile: 'about.html',
    bodyClass:  'static-page about-page',
    title:      'About Poki2 — Our Mission, Team & Advertising',
    description:'Learn about Poki2, the free browser games network. Our mission, how we curate games, our advertising policy, and who we are.',
    canonical:  'https://poki2.online/about',
    schema: [{
      '@context': 'https://schema.org',
      '@type': 'AboutPage',
      url:  'https://poki2.online/about',
      name: 'About Poki2',
      description: 'About the Poki2 free browser games network.',
    }],
  },
  {
    slug:       'privacy',
    outputFile: 'privacy.html',
    bodyClass:  'static-page privacy-page',
    title:      'Privacy Policy — Poki2',
    description:'Poki2 Privacy Policy: how we collect, use, and protect your data, including our use of Google AdSense advertising cookies.',
    canonical:  'https://poki2.online/privacy',
    schema: [{
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      url: 'https://poki2.online/privacy',
      name: 'Privacy Policy — Poki2',
    }],
  },
  {
    slug:       'terms',
    outputFile: 'terms.html',
    bodyClass:  'static-page terms-page',
    title:      'Terms of Use — Poki2',
    description:'Poki2 Terms of Use: acceptable use, intellectual property, disclaimers and your rights as a visitor.',
    canonical:  'https://poki2.online/terms',
    schema: [{
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      url: 'https://poki2.online/terms',
      name: 'Terms of Use — Poki2',
    }],
  },
  {
    slug:       'contact',
    outputFile: 'contact.html',
    bodyClass:  'static-page contact-page',
    title:      'Contact Us — Poki2',
    description:'Contact the Poki2 team for support, game submissions, partnership enquiries, or press requests.',
    canonical:  'https://poki2.online/contact',
    schema: [{
      '@context': 'https://schema.org',
      '@type': 'ContactPage',
      url: 'https://poki2.online/contact',
      name: 'Contact Poki2',
    }],
  },
  {
    slug:       'dmca',
    outputFile: 'dmca.html',
    bodyClass:  'static-page dmca-page',
    title:      'DMCA Notice — Poki2',
    description:'Poki2 DMCA policy. How to submit a copyright removal request and what to expect.',
    canonical:  'https://poki2.online/dmca',
    schema: [{
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      url: 'https://poki2.online/dmca',
      name: 'DMCA Notice — Poki2',
    }],
  },
];

// ── Blog articles metadata ────────────────────────────────────────────────────
const blogPosts = [
  {
    slug:       'best-browser-games-2026',
    title:      'The 15 Best Free Browser Games of 2026',
    description:'Our editors picked the 15 best free browser games you can play right now — no download, no login, just open and play.',
    date:       'April 2, 2026',
    isoDate:    '2026-04-02',
    category:   'Top Lists',
    readTime:   '8 min read',
  },
  {
    slug:       'what-are-io-games',
    title:      'What Are .IO Games? Your Complete Guide',
    description:'.IO games are lightweight multiplayer browser games. Learn what makes them special, which ones are the best, and where to play them free.',
    date:       'March 28, 2026',
    isoDate:    '2026-03-28',
    category:   'Guides',
    readTime:   '7 min read',
  },
  {
    slug:       'unblocked-games-guide',
    title:      'How to Play Unblocked Games Safely at School or Work',
    description:'A practical guide to finding and playing unblocked browser games legally and safely, without putting your network access at risk.',
    date:       'March 20, 2026',
    isoDate:    '2026-03-20',
    category:   'Guides',
    readTime:   '6 min read',
  },
  {
    slug:       'best-multiplayer-browser-games',
    title:      '10 Best Multiplayer Browser Games You Can Play Right Now',
    description:'Compete against real players in these top multiplayer games. No downloads, no accounts — just open your browser and start playing.',
    date:       'March 12, 2026',
    isoDate:    '2026-03-12',
    category:   'Top Lists',
    readTime:   '7 min read',
  },
  {
    slug:       'game-aggregator-picks',
    title:      'Our Top 5 Browser Game Picks for Every Type of Gamer',
    description:'Whether you love puzzles, racing, action, or casual fun — we\'ve picked the single best browser game for each type of player.',
    date:       'March 5, 2026',
    isoDate:    '2026-03-05',
    category:   'Reviews',
    readTime:   '6 min read',
  },
  {
    slug:       'best-2-player-browser-games',
    title:      '10 Best 2-Player Browser Games to Play with a Friend',
    description:'Play together on one keyboard or across the internet — these are the best free 2-player browser games available right now, no download needed.',
    date:       'April 3, 2026',
    isoDate:    '2026-04-03',
    category:   'Top Lists',
    readTime:   '7 min read',
  },
  {
    slug:       'best-unblocked-io-games-school',
    title:      'Top 10 Unblocked IO Games for School in 2026',
    description:'Looking for IO games that work on school Chromebooks and bypass most content filters? Here are 10 unblocked IO games you can actually play.',
    date:       'March 30, 2026',
    isoDate:    '2026-03-30',
    category:   'Top Lists',
    readTime:   '6 min read',
  },
  {
    slug:       'best-racing-browser-games',
    title:      'Best Free Racing Browser Games: Drift Hunters, Moto X3M & More',
    description:'From arcade drift cars to off-road stunt bikes — the definitive list of the best free racing games you can play in your browser right now.',
    date:       'March 18, 2026',
    isoDate:    '2026-03-18',
    category:   'Top Lists',
    readTime:   '7 min read',
  },
  {
    slug:       'best-puzzle-browser-games',
    title:      '15 Best Free Puzzle Browser Games You Can Play Right Now',
    description:'Brain teasers, match-3, logic puzzles, and word games — the best free puzzle browser games ranked by quality, replayability, and zero-download access.',
    date:       'March 10, 2026',
    isoDate:    '2026-03-10',
    category:   'Top Lists',
    readTime:   '8 min read',
  },
  {
    slug:       'browser-games-no-download',
    title:      'How to Play Browser Games Without Downloading Anything',
    description:'A complete guide to free browser gaming — what browser games are, why they\'re safer than downloads, and how to get the best experience on any device.',
    date:       'March 3, 2026',
    isoDate:    '2026-03-03',
    category:   'Guides',
    readTime:   '7 min read',
  },
  {
    slug:       'best-action-browser-games',
    title:      'Top 10 Best Free Action Browser Games in 2026',
    description:'From browser FPS to ragdoll fighters — our definitive list of the best free action browser games you can play instantly, no download, no install.',
    date:       'April 4, 2026',
    isoDate:    '2026-04-04',
    category:   'Top Lists',
    readTime:   '8 min read',
  },
  {
    slug:       'unblocked-games-at-school-2026',
    title:      '12 Unblocked Games That Actually Work at School in 2026',
    description:'A practical guide to browser games that work on school Chromebooks and strict networks — including Google built-ins, NYT Games, and verified unblocked portals.',
    date:       'April 4, 2026',
    isoDate:    '2026-04-04',
    category:   'Guides',
    readTime:   '8 min read',
  },
  {
    slug:       'best-idle-clicker-browser-games',
    title:      '8 Best Idle &amp; Clicker Browser Games to Play in 2026',
    description:'Cookie Clicker, Clicker Heroes, Realm Grinder and more — the best idle and incremental browser games ranked by depth, replayability, and session flexibility.',
    date:       'April 5, 2026',
    isoDate:    '2026-04-05',
    category:   'Top Lists',
    readTime:   '7 min read',
  },
  {
    slug:       'best-mobile-browser-games',
    title:      'Best Browser Games to Play on Your Phone (No App Needed)',
    description:'10 browser games with excellent mobile touch controls — play Slither.io, Cut the Rope, 2048, and more directly in your phone browser, no app install required.',
    date:       'April 5, 2026',
    isoDate:    '2026-04-05',
    category:   'Top Lists',
    readTime:   '7 min read',
  },
  {
    slug:       'best-strategy-browser-games',
    title:      '12 Best Strategy Browser Games in 2026 (Free to Play)',
    description:'Forge of Empires, OGame, Tribal Wars, Diep.io and more — the best free strategy browser games ranked from casual city builders to deep 4X multiplayer.',
    date:       'April 6, 2026',
    isoDate:    '2026-04-06',
    category:   'Top Lists',
    readTime:   '9 min read',
  },
  {
    slug:       'geometry-dash-complete-guide',
    title:      'Geometry Dash: Complete Guide to Every Level & Mechanic',
    description:'Master every official Geometry Dash level with our complete guide — all 21 levels explained, secret coins, game modes, and tips for beginners through experts.',
    date:       'April 7, 2026',
    isoDate:    '2026-04-07',
    category:   'Guides',
    readTime:   '9 min read',
  },
  {
    slug:       'unblocked-games-chromebook-guide',
    title:      'Best Unblocked Games for School Chromebooks in 2026',
    description:'A complete guide to playing unblocked games on school Chromebooks — how game blocking works, how to find safe sites, and 10 games that work on strict school networks.',
    date:       'April 7, 2026',
    isoDate:    '2026-04-07',
    category:   'Guides',
    readTime:   '8 min read',
  },
  {
    slug:       'cookie-clicker-complete-guide',
    title:      'Cookie Clicker Complete Guide: Grandmapocalypse, Prestige & Tips',
    description:'Everything you need to know about Cookie Clicker — all buildings explained, the Grandmapocalypse walkthrough, golden cookie combos, and the prestige/ascension system.',
    date:       'April 8, 2026',
    isoDate:    '2026-04-08',
    category:   'Guides',
    readTime:   '9 min read',
  },
  {
    slug:       'best-2-player-games-guide',
    title:      'Best Two-Player Browser Games: The Complete Guide',
    description:'8 two-player browser games with full controls listed — whether you\'re on the same keyboard or playing across the internet, these are the best options available.',
    date:       'April 8, 2026',
    isoDate:    '2026-04-08',
    category:   'Top Lists',
    readTime:   '8 min read',
  },
  {
    slug:       'beginners-guide-to-browser-games',
    title:      "Beginner's Guide to Browser Games: What They Are and Where to Start",
    description:'New to browser gaming? This complete beginner\'s guide explains what HTML5 games are, how they compare to console games, and which titles to start with by playstyle.',
    date:       'April 9, 2026',
    isoDate:    '2026-04-09',
    category:   'Guides',
    readTime:   '8 min read',
  },
  {
    slug:       'best-sports-browser-games',
    title:      'Best Sports Browser Games 2026: Basketball, Tennis, Baseball & More',
    description:'The best free sports browser games in 2026 — Basketball Stars, Retro Bowl, Arcade Tennis, Ball Orbit, Bat Smash, Arcade Volley, and Billiards Master. No download required.',
    date:       'April 9, 2026',
    isoDate:    '2026-04-09',
    category:   'Sports & IO',
    readTime:   '7 min read',
  },
  {
    slug:       'italian-brainrot-games-guide',
    title:      'Italian Brainrot Games: The Complete Guide to Every Meme Browser Game',
    description:'Your complete guide to Italian Brainrot browser games — Bombardino Crocodilo Clicker, Chicken Jockey Clicker, 2048 Italian Brainrot, Chicken Jockey Combat, and more.',
    date:       'April 9, 2026',
    isoDate:    '2026-04-09',
    category:   'Trending',
    readTime:   '6 min read',
  },
  {
    slug:       'best-simulation-adventure-browser-games',
    title:      'Best Simulation & Adventure Browser Games 2026: Age of War, Animal Craft & More',
    description:'Top free simulation and adventure browser games in 2026 — Age of War, Animal Craft, Crazy Animal City, Astro Tycoon, Astro Robot Clicker, American Truck Driving, and more.',
    date:       'April 9, 2026',
    isoDate:    '2026-04-09',
    category:   'Platformer & Arcade',
    readTime:   '8 min read',
  },
  {
    slug:       'best-2048-variant-games',
    title:      'Best 2048 Variant Games to Play in 2026: Drop, Rogue, Italian Brainrot & More',
    description:'Beyond the original, 2048 has spawned brilliant variants — 2048 Drop, 2048 Rogue, and 2048 Italian Brainrot. This guide covers every variant and the strategy that wins each one.',
    date:       'April 10, 2026',
    isoDate:    '2026-04-10',
    category:   'Puzzle',
    readTime:   '6 min read',
  },
  {
    slug:       'best-shooting-browser-games',
    title:      'Best Shooting Browser Games 2026: Blocky Hunter, Shell Shockers, Bricky Break & More',
    description:'Top free shooting browser games in 2026 — Blocky Hunter, Chicken Jockey Combat, Bricky Break, Shell Shockers, 1v1.LOL, and more. No download, no install, just play.',
    date:       'April 10, 2026',
    isoDate:    '2026-04-10',
    category:   'Action & Shooter',
    readTime:   '7 min read',
  },
  {
    slug:       'best-racing-driving-browser-games',
    title:      'Best Racing & Driving Browser Games 2026: Bike Xtreme, Drift Hunters, Truck Driving & More',
    description:'Top free racing and driving browser games in 2026 — Bike Xtreme, Drift Hunters, American Truck Driving, Blocky Rider, Battle Karts, and more. Zero downloads required.',
    date:       'April 10, 2026',
    isoDate:    '2026-04-10',
    category:   'Racing',
    readTime:   '7 min read',
  },
];
// ── Individual game pages ─────────────────────────────────────────────────────
const gamePosts = [
  {
    slug:      '2048',
    title:     '2048',
    description: 'Play 2048 free in your browser — no download, no account. Slide numbered tiles and combine them to reach the 2048 tile in this classic puzzle game.',
    embedUrl:  'https://azgames.io/2048.embed',
    imgUrl:    '/imgs/fgame/2048.jpg',
    genre:     'Puzzle',
    category:  'Puzzle',
    players:   '1 Player',
    controls:  'Arrow Keys / WASD / Swipe',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'slope',
    title:     'Slope',
    description: 'Play Slope free online — guide a ball down an infinite 3D slope, dodge obstacles, and survive as long as possible. A fast-paced endless runner with simple controls.',
    embedUrl:  'https://azgames.io/slope.embed',
    imgUrl:    '/imgs/fgame/slope.png',
    genre:     'Endless Runner',
    category:  'Endless Runner',
    players:   '1 Player',
    controls:  'Arrow Keys / A–D',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      '1v1lol',
    title:     '1v1.LOL',
    description: 'Play 1v1.LOL free online — the browser-based building-and-shooting game. Practice your building mechanics and aim in real-time PvP matches, no download needed.',
    embedUrl:  'https://azgames.io/1v1lol.embed',
    imgUrl:    '/imgs/fgame/1v1lol.png',
    genre:     'Action / Shooter',
    category:  'Action & Shooter',
    players:   '1–2 Players',
    controls:  'WASD + Mouse / Z to build',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'cookie-clicker',
    title:     'Cookie Clicker',
    description: 'Play Cookie Clicker free in your browser — click to bake cookies, buy buildings, survive the Grandmapocalypse, and ascend with prestige upgrades in this iconic idle game.',
    embedUrl:  'https://azgames.io/cookie-clicker.embed',
    imgUrl:    '/imgs/fgame/cookie-clicker.png',
    genre:     'Idle / Clicker',
    category:  'Idle & Sandbox',
    players:   '1 Player',
    controls:  'Mouse Click',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'run-3',
    title:     'Run 3',
    description: 'Play Run 3 free online — an endless space runner where you guide an alien through crumbling tunnels in outer space. Jump, rotate the tunnel, and keep running.',
    embedUrl:  'https://azgames.io/run-3.embed',
    imgUrl:    '/imgs/fgame/run-3.png',
    genre:     'Endless Runner',
    category:  'Endless Runner',
    players:   '1 Player',
    controls:  'Arrow Keys / WASD / Spacebar',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'stickman-hook',
    title:     'Stickman Hook',
    description: 'Play Stickman Hook free in your browser — swing through levels using a grappling hook as a stickman character. Master the momentum physics for fluid, satisfying movement.',
    embedUrl:  'https://azgames.io/stickman-hook.embed',
    imgUrl:    '/imgs/fgame/stickman-hook.jpg',
    genre:     'Skill / Platformer',
    category:  'Platformer & Arcade',
    players:   '1 Player',
    controls:  'Mouse Click / Tap',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'drift-hunters',
    title:     'Drift Hunters',
    description: 'Play Drift Hunters free online — a realistic 3D drift racing game with tunable cars. Earn points by drifting, upgrade your vehicle, and unlock new tracks and drift machines.',
    embedUrl:  'https://azgames.io/drift-hunters.embed',
    imgUrl:    '/imgs/fgame/drift-hunters.jpg',
    genre:     'Racing',
    category:  'Racing',
    players:   '1 Player',
    controls:  'Arrow Keys / WASD',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'moto-x3m',
    title:     'Moto X3M',
    description: 'Play Moto X3M free in your browser — a stunt motorbike game featuring increasingly difficult obstacle courses. Perform backflips and wheelies to earn stars on each level.',
    embedUrl:  'https://azgames.io/moto-x3m.embed',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
    imgUrl:    '/imgs/fgame/moto-x3m.png',
    genre:     'Stunt Racing',
    category:  'Racing',
    players:   '1 Player',
    controls:  'Arrow Keys',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'shell-shockers',
    title:     'Shell Shockers',
    description: 'Play Shell Shockers free online — a multiplayer first-person shooter where you play as an egg. Choose your weapon class, frag opponents, and dominate egg-based warfare.',
    embedUrl:  'https://azgames.io/shell-shockers.embed',
    imgUrl:    '/imgs/fgame/shell-shockers.jpg',
    genre:     'Multiplayer FPS',
    category:  'Action & Shooter',
    players:   'Multiplayer',
    controls:  'WASD + Mouse',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'tetris',
    title:     'Tetris',
    description: 'Play Tetris free in your browser — the original falling-block puzzle game. Arrange tetrominoes to clear lines, score points, and survive as the blocks speed up.',
    embedUrl:  'https://azgames.io/tetris.embed',
    imgUrl:    '/imgs/fgame/tetris.png',
    genre:     'Puzzle',
    category:  'Puzzle',
    players:   '1 Player',
    controls:  'Arrow Keys',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'basketball-stars',
    title:     'Basketball Stars',
    description: 'Play Basketball Stars free online — a 1v1 street basketball game with dribbling mechanics, trick shots, and PvP matches. Challenge AI or a friend in head-to-head basketball.',
    embedUrl:  'https://azgames.io/basketball-stars.embed',
    imgUrl:    '/imgs/fgame/basketball-stars.png',
    genre:     'Sports',
    category:  'Sports & IO',
    players:   '1–2 Players',
    controls:  'Arrow Keys / Mouse',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'crossy-road',
    title:     'Crossy Road',
    description: 'Play Crossy Road free in your browser — hop across roads, rivers, and rail tracks without getting hit. The further you go, the harder it gets in this endless arcade hopper.',
    embedUrl:  'https://azgames.io/crossy-road.embed',
    imgUrl:    '/imgs/fgame/crossy-road.png',
    genre:     'Arcade',
    category:  'Endless Runner',
    players:   '1 Player',
    controls:  'Arrow Keys / WASD / Swipe',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'pacman',
    title:     'Pac-Man 30th Anniversary',
    description: 'Play the Google Pac-Man 30th Anniversary edition free in your browser — guide the iconic yellow character through mazes, eat all the dots, and avoid ghosts. A timeless arcade classic.',
    embedUrl:  'https://azgames.io/pacman-30th-anniversary.embed',
    imgUrl:    '/imgs/fgame/pacman.jpg',
    genre:     'Arcade',
    category:  'Platformer & Arcade',
    players:   '1–2 Players',
    controls:  'Arrow Keys / WASD',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'retro-bowl',
    title:     'Retro Bowl',
    description: 'Play Retro Bowl free in your browser — a retro-style American football game where you manage and play as a team. Call plays, throw passes, and lead your squad to championship glory.',
    embedUrl:  'https://azgames.io/retro-bowl.embed',
    imgUrl:    '/imgs/fgame/retro-bowl.jpg',
    genre:     'Sports',
    category:  'Sports & IO',
    players:   '1 Player',
    controls:  'Mouse / Touch',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'geometry-dash',
    title:     'Geometry Dash',
    description: 'Play Geometry Dash free in your browser — time your jumps to the beat of the music, avoid spikes and saws, and complete rhythmic obstacle courses. A browser-playable version of the hit game.',
    embedUrl:  'https://azgames.io/geometry-dash.embed',
    imgUrl:    '/imgs/fgame/geometry-dash.png',
    genre:     'Rhythm Platformer',
    category:  'Platformer & Arcade',
    players:   '1 Player',
    controls:  'Spacebar / Click / Tap',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'fireboy-and-watergirl',
    title:     'Fireboy and Watergirl',
    description: 'Play Fireboy and Watergirl free online — a legendary 2-player co-op puzzle platformer. Guide fire and water characters through elemental temples, solve puzzles, and reach the exit together.',
    embedUrl:  'https://azgames.io/fireboy-and-watergirl.embed',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
    imgUrl:    '/imgs/fgame/fireboy-watergirl-1.png',
    genre:     '2-Player Co-op',
    category:  'Platformer & Arcade',
    players:   '1–2 Players',
    controls:  'WASD (Fire) / Arrow Keys (Water)',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'smash-karts',
    title:     'Smash Karts',
    description: 'Play Smash Karts free online — a 3D multiplayer kart battle arena game. Drive your kart, collect weapons, and blast opponents in chaotic real-time matches against players worldwide.',
    embedUrl:  'https://azgames.io/smash-karts.embed',
    imgUrl:    '/imgs/fgame/smash-karts.jpg',
    genre:     'Multiplayer Racing',
    category:  'Racing',
    players:   'Multiplayer',
    controls:  'WASD + Mouse',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'vex-3',
    title:     'Vex 3',
    description: 'Play Vex 3 free in your browser — a challenging stickman platformer with increasingly devious obstacle courses. Master the wall-jumps, spikes, and moving platforms to survive each act.',
    embedUrl:  'https://azgames.io/vex-3.embed',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
    imgUrl:    '/imgs/fgame/vex3v.jpg',
    genre:     'Stickman Platformer',
    category:  'Platformer & Arcade',
    players:   '1 Player',
    controls:  'WASD / Arrow Keys',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'subway-surfers',
    title:     'Subway Surfers',
    description: 'Play Subway Surfers free online — dash, jump, and dodge trains as a graffiti artist being chased by an inspector. Collect coins, hoverboards, and unlock characters in this endless runner.',
    embedUrl:  'https://azgames.io/subway-surfers.embed',
    imgUrl:    '/imgs/fgame/subway-surfers.png',
    genre:     'Endless Runner',
    category:  'Endless Runner',
    players:   '1 Player',
    controls:  'Arrow Keys / Swipe',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
  },
  {
    slug:      'paper-io',
    title:     'Paper.io',
    description: 'Play Paper.io free online — claim territory on an endless grid by drawing loops without getting cut. The more land you capture without being intercepted, the higher your score in this addictive IO game.',
    embedUrl:  'https://azgames.io/paper-io.embed',
    imgUrl:    '/imgs/fgame/paper-io.jpeg',
    genre:     'IO Multiplayer',
    category:  'Sports & IO',
    players:   'Multiplayer',
    controls:  'Mouse / Touch / Arrow Keys',
    date:      'April 7, 2026',
    isoDate:   '2026-04-07',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
  },
  {
    slug:      'color-switch',
    title:     'Color Switch',
    description: 'A fast-paced reflex arcade game — tap to pass a ball through matching-colour obstacles and chain combos.',
    embedUrl:  'https://azgames.io/color-switch.embed',
    imgUrl:    '/imgs/fgame/color-switch.png',
    genre:     'Arcade',
    category:  'Platformer & Arcade',
    players:   '1 Player',
    controls:  'Click / Tap',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
  },
  {
    slug:      'cut-the-rope',
    title:     'Cut the Rope',
    description: 'Physics-based puzzle challenges — cut ropes in the right order to feed candy to Om Nom and collect stars.',
    embedUrl:  'https://azgames.io/cut-the-rope.embed',
    imgUrl:    '/imgs/fgame/cut-the-rope.png',
    genre:     'Puzzle',
    category:  'Puzzle',
    players:   '1 Player',
    controls:  'Mouse / Tap',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
  },
  {
    slug:      'hill-climb-racing',
    title:     'Hill Climb Racing',
    description: 'Drive across uneven terrain, upgrade your vehicle, and master the physics to reach further stages.',
    embedUrl:  'https://azgames.io/hill-climb-racing.embed',
    imgUrl:    '/imgs/fgame/hill-climb-racing.png',
    genre:     'Racing',
    category:  'Racing',
    players:   '1 Player',
    controls:  'Arrow Keys',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
  },
  {
    slug:      'slither-io',
    title:     'Slither.io',
    description: 'Grow your snake by eating glowing orbs and outmaneuver other players in this classic IO survival game.',
    embedUrl:  'https://azgames.io/slither-io.embed',
    imgUrl:    '/imgs/fgame/slither-io.png',
    genre:     'IO Multiplayer',
    category:  'Sports & IO',
    players:   'Multiplayer',
    controls:  'Mouse / Touch',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'agar-io',
    title:     'Agar.io',
    description: 'Control a cell, eat smaller cells to grow, and avoid larger predators in this massively multiplayer IO arena.',
    embedUrl:  'https://azgames.io/agar-io.embed',
    imgUrl:    '/imgs/fgame/agar-io.png',
    genre:     'IO Multiplayer',
    category:  'Sports & IO',
    players:   'Multiplayer',
    controls:  'Mouse / Touch',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
  },
  {
    slug:      'krunker-io',
    title:     'Krunker.io',
    description: 'Fast-paced browser FPS with pixel graphics — aim, jump, and dominate quick round matches.',
    embedUrl:  'https://azgames.io/krunker-io.embed',
    imgUrl:    '/imgs/fgame/krunker-io.png',
    genre:     'Shooter',
    category:  'Action & Shooter',
    players:   'Multiplayer',
    controls:  'WASD + Mouse',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
  },
  {
    slug:      'soccer-random',
    title:     'Soccer Random',
    description: 'Chaotic browser soccer where physics rules — play quick matches with simple two-button controls.',
    embedUrl:  'https://azgames.io/soccer-random.embed',
    imgUrl:    '/imgs/fgame/soccer-random.png',
    genre:     'Sports',
    category:  'Sports & IO',
    players:   '1–4 Players',
    controls:  'Arrow Keys / Z / X',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
  },,
{
    slug:      '2048-drop',
    title:     '2048 Drop',
    description: 'Game 2048 Drop challenges you to merge chips strategically to create the ultimate number 2048. Dive into this addictive game!',
    embedUrl:  'https://azgames.io/2048-drop.embed',
    imgUrl:    '/imgs/fgame/2048-drop.png',
    genre:     'Puzzle',
    category:  'Puzzle',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      '2048-italian-brainrot',
    title:     '2048 Italian Brainrot',
    description: '2048 Italian Brainrot is a fun block puzzle game that blends the classic 2048 gameplay with the viral charm of Italian Brainrot characters. Play on Azgames now!',
    embedUrl:  'https://azgames.io/2048-italian-brainrot.embed',
    imgUrl:    '/imgs/fgame/2048-italian-brainrot.png',
    genre:     'Puzzle',
    category:  'Puzzle',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      '2048-rogue',
    title:     '2048 Rogue',
    description: 'Set on a 4x4 grid, 2048 Rogue is an addictive yet challenging merging puzzle game where you combine tiles for higher-value creatures or objects. Play now & have fun!',
    embedUrl:  'https://azgames.io/2048-rogue.embed',
    imgUrl:    '/imgs/fgame/2048-rogue.png',
    genre:     'Puzzle',
    category:  'Puzzle',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'age-of-war',
    title:     'Age Of War',
    description: 'Age of War is an online strategy game in which users create and advance a civilization from the Stone Age to the present age.',
    embedUrl:  'https://azgames.io/age-of-war.embed',
    imgUrl:    '/imgs/fgame/age-of-war.jpg',
    genre:     'Casual',
    category:  'Platformer & Arcade',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'american-truck-driving',
    title:     'American Truck Driving',
    description: 'America Truck Driving is a 3D driving simulation game where players experience the job of a truck driver in realistic driving gameplay. Play on Azgames today!',
    embedUrl:  'https://azgames.io/american-truck-driving.embed',
    imgUrl:    '/imgs/fgame/american-truck-driving.png',
    genre:     'Racing & Driving',
    category:  'Racing',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'animal-craft',
    title:     'Animal Craft',
    description: 'Animal Craft is a quirky animal fusion and battle survival game where you combine different animals to create bizarre hybrids, then explore, battle, and survive.',
    embedUrl:  'https://azgames.io/animal-craft.embed',
    imgUrl:    '/imgs/fgame/animal-craft.png',
    genre:     'Arcade',
    category:  'Platformer & Arcade',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'arcade-tennis',
    title:     'Arcade Tennis',
    description: 'Arcade Tennis is a fun arcade sports game where you play as a quirky tennis player and aim to dominate the court with your precision and powerful strikes. Enjoy it!',
    embedUrl:  'https://azgames.io/arcade-tennis.embed',
    imgUrl:    '/imgs/fgame/arcade-tennis.png',
    genre:     'Sports',
    category:  'Sports & IO',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'arcade-volley',
    title:     'Arcade Volley',
    description: 'Jump in, join quick volleyball matches across a variety of court locations in Arcade Volley. Enjoy fun, fast-paced matches and hit powerful spikes to earn scores.',
    embedUrl:  'https://azgames.io/arcade-volley.embed',
    imgUrl:    '/imgs/fgame/arcade-volley.png',
    genre:     '2 Player',
    category:  'Sports & IO',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'astro-robot-clicker',
    title:     'Astro Robot Clicker',
    description: 'Astro Robot Clicker is the best clicker game, transporting you to a thrilling space journey! Get ready to discover the universe',
    embedUrl:  'https://azgames.io/astro-robot-clicker.embed',
    imgUrl:    '/imgs/fgame/astro-robot-clicker.png',
    genre:     'Clicker',
    category:  'Idle & Sandbox',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'astro-tycoon',
    title:     'Astro Tycoon',
    description: 'Astro Tycoon is a casual space-themed idle game that drops you into a special space-mining adventure. Play now, collect minerals, and go to even the farthest planet.',
    embedUrl:  'https://azgames.io/astro-tycoon.embed',
    imgUrl:    '/imgs/fgame/astro-tycoon.png',
    genre:     'Arcade',
    category:  'Platformer & Arcade',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'ball-orbit',
    title:     'Ball Orbit',
    description: 'Hit your baseball the farthest distance possible in Ball Orbit: Unleash the perfect hit, earn rewards, and upgrade your ball to make it fly farther and farther.',
    embedUrl:  'https://azgames.io/ball-orbit.embed',
    imgUrl:    '/imgs/fgame/ball-orbit.png',
    genre:     'Sports',
    category:  'Sports & IO',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'basket-random',
    title:     'Basket Random',
    description: 'Basket Random is a fun two-player basketball sports game. The object is to score as many goals as possible to beat your opponent and get more points.',
    embedUrl:  'https://azgames.io/basket-random.embed',
    imgUrl:    '/imgs/fgame/basket-random.jpeg',
    genre:     '2 Player',
    category:  'Sports & IO',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
  },
  {
    slug:      'bat-smash',
    title:     'Bat Smash',
    description: 'Bat Smash is a fun, casual sports game where your goal is to swing your bat at the perfect timing to send the baseball as far as possible, earn money, and upgrade.',
    embedUrl:  'https://azgames.io/bat-smash.embed',
    imgUrl:    '/imgs/fgame/bat-smash.png',
    genre:     'Sports',
    category:  'Sports & IO',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'battle-karts',
    title:     'Battle Karts',
    description: 'Battle Karts Join the ultimate free multiplayer kart battle arena. Drive fast Unleash rockets Create epic explosions. Play now for endless thrills',
    embedUrl:  'https://azgames.io/battle-karts.embed',
    imgUrl:    '/imgs/fgame/battle-karts.png',
    genre:     'IO Multiplayer',
    category:  'Sports & IO',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'bike-xtreme',
    title:     'Bike Xtreme',
    description: 'Bike Xtreme is an exciting racing game. Test your skills with smooth controls and thrilling jumps in this adventure. Ready to ride through rugged terrains?',
    embedUrl:  'https://azgames.io/bike-xtreme.embed',
    imgUrl:    '/imgs/fgame/bike-xtreme.png',
    genre:     'Racing & Driving',
    category:  'Racing',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'billiards-master',
    title:     'Billiards Master',
    description: 'Dive in Billiards Master realistic billiards simulation gameplay. Select a mode you love, aim, control shot strength, and strike the ball. Play on Azgames today!',
    embedUrl:  'https://azgames.io/billiards-master.embed',
    imgUrl:    '/imgs/fgame/billiards-master.png',
    genre:     'IO Multiplayer',
    category:  'Sports & IO',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'bitlife',
    title:     'Bitlife',
    description: 'BitLife is a text-based life simulation game. Here you can make every decision about your life, from birth to death. Each choice will create a unique and unpredictable life story.',
    embedUrl:  'https://azgames.io/bitlife.embed',
    imgUrl:    '/imgs/fgame/bitlife.png',
    genre:     'Arcade',
    category:  'Platformer & Arcade',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
    deprecated: true,
    deprecationReason: 'Access denied. Authorization required."',
  },
  {
    slug:      'blocky-hunter',
    title:     'Blocky Hunter',
    description: 'Gear up for intense zombie battles in Blocky Hunter! Armed with powerful weapons, take on relentless waves of the undead, including fearsome boss zombies.',
    embedUrl:  'https://azgames.io/blocky-hunter.embed',
    imgUrl:    '/imgs/fgame/blocky-hunter.png',
    genre:     'Shooter',
    category:  'Action & Shooter',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'blocky-rider',
    title:     'Blocky Rider',
    description: 'Blocky Rider is a block-style motorcycle racing game where players ride bikes across city streets full of traffic, obstacles, and crashes. Explore all game modes now!',
    embedUrl:  'https://azgames.io/blocky-rider.embed',
    imgUrl:    '/imgs/fgame/blocky-rider.png',
    genre:     'Racing & Driving',
    category:  'Racing',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'bombardino-crocodilo-clicker',
    title:     'Bombardino Crocodilo Clicker',
    description: 'Bombardino Crocodilo Clicker is an Italian Brainrot meme-themed clicker where players click/tap repeatedly on Bombardino Crocodilo to earn coins. Enjoy on AZgames today!',
    embedUrl:  'https://azgames.io/bombardino-crocodilo-clicker.embed',
    imgUrl:    '/imgs/fgame/bombardino-crocodilo-clicker.png',
    genre:     'Clicker',
    category:  'Idle & Sandbox',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'bricky-break',
    title:     'Bricky Break',
    description: 'Bricky Break is a fun and simple arcade blast! Launch balls, break bricks, and collect more balls for a chain reaction. Relaxing gameplay, challenging levels. Play now!',
    embedUrl:  'https://azgames.io/bricky-break.embed',
    imgUrl:    '/imgs/fgame/bricky-break.png',
    genre:     'Shooter',
    category:  'Action & Shooter',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'chicken-jockey-clicker',
    title:     'Chicken Jockey Clicker',
    description: 'Chicken Jockey Clicker is a casual idle clicker game featuring Chicken Jockey characters. Click to earn points and spend them on upgrades to boost scores faster.',
    embedUrl:  'https://azgames.io/chicken-jockey-clicker.embed',
    imgUrl:    '/imgs/fgame/chicken-jockey-clicker.png',
    genre:     'Clicker',
    category:  'Idle & Sandbox',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'chicken-jockey-combat',
    title:     'Chicken Jockey Combat',
    description: 'Chicken Jockey Combat is a first-person zombie survival shooter game where players must defend themselves and their base against relentless waves of zombies.',
    embedUrl:  'https://azgames.io/chicken-jockey-combat.embed',
    imgUrl:    '/imgs/fgame/chicken-jockey-combat.png',
    genre:     'Shooter',
    category:  'Action & Shooter',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  },
  {
    slug:      'crazy-animal-city',
    title:     'Crazy Animal City',
    description: 'Set in an expansive open-world environment, Crazy Animal City is a 3D animal simulator where players control various animals and cause wild chaos and mayhem.',
    embedUrl:  'https://azgames.io/crazy-animal-city.embed',
    imgUrl:    '/imgs/fgame/crazy-animal-city.png',
    genre:     'Adventure',
    category:  'Platformer & Arcade',
    players:   '1 Player',
    controls:  'Mouse / Keyboard',
    date:      'April 8, 2026',
    isoDate:   '2026-04-08',
  }
];
module.exports = { site, network, pages, blogPosts, gamePosts };

